version: "3"

services:
  db:
    image: mariadb:10
    ports:
      - 4406:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bootex
      MYSQL_USER: bootuser
      MYSQL_PASSWORD: bootuser
      TZ: Asia/Seoul
    networks:
      - backend
    restart: always

networks:
  backend: